// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxwhItN2sBVEO0-yr81rhaRRBsL7HSbbo',
    appId: '1:537125186662:web:3369a367f7ac7339b7d1a7',
    messagingSenderId: '537125186662',
    projectId: 'laptrinhmobile-1ed65',
    authDomain: 'laptrinhmobile-1ed65.firebaseapp.com',
    storageBucket: 'laptrinhmobile-1ed65.firebasestorage.app',
    measurementId: 'G-SVLWC0BZDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHYT4r5HwtctktHqJnC6XxBEPVie5Lhf0',
    appId: '1:537125186662:android:8a0383059290967fb7d1a7',
    messagingSenderId: '537125186662',
    projectId: 'laptrinhmobile-1ed65',
    storageBucket: 'laptrinhmobile-1ed65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhRD96_HNE39uWBWIK2KH21KYh4Krfe8g',
    appId: '1:537125186662:ios:e4179cb7cf2b4b1eb7d1a7',
    messagingSenderId: '537125186662',
    projectId: 'laptrinhmobile-1ed65',
    storageBucket: 'laptrinhmobile-1ed65.firebasestorage.app',
    iosBundleId: 'com.example.doanlaptrinhmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhRD96_HNE39uWBWIK2KH21KYh4Krfe8g',
    appId: '1:537125186662:ios:e4179cb7cf2b4b1eb7d1a7',
    messagingSenderId: '537125186662',
    projectId: 'laptrinhmobile-1ed65',
    storageBucket: 'laptrinhmobile-1ed65.firebasestorage.app',
    iosBundleId: 'com.example.doanlaptrinhmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxwhItN2sBVEO0-yr81rhaRRBsL7HSbbo',
    appId: '1:537125186662:web:de1d5619d1116425b7d1a7',
    messagingSenderId: '537125186662',
    projectId: 'laptrinhmobile-1ed65',
    authDomain: 'laptrinhmobile-1ed65.firebaseapp.com',
    storageBucket: 'laptrinhmobile-1ed65.firebasestorage.app',
    measurementId: 'G-23KQSJ63BY',
  );
}
